id: IC44A74F6
legacy_id: P009371
ocr_import_info:
  bdrc_scan_id: W4CZ45268
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T05:02:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:33:42.569836+00:00'
last_modified: 2022-09-04 02:33:51.742471
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ45268
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ45268
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་ཆེན་གྱི་འཁྲིད་ཡིག་མན་ངག་ཞལ་ཤེས་དང་བཅས་པའི་ཁ་ཆེམས་རླུང་ལ་བསྐུར་བའི་འཕྲིན་ཡིག
  author: རྒྱལ་རོང་ཚུལ་ཁྲིམས་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.7754249993307394
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I4CZ45280:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ45280
      total_pages: 254
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ45280.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7754249993307394
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
