id: P009371
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:35:39.862710
source_metadata:
  id: bdr:W4CZ45268
  title: ཕྱག་ཆེན་གྱི་འཁྲིད་ཡིག་མན་ངག་ཞལ་ཤེས་དང་བཅས་པའི་ཁ་ཆེམས་རླུང་ལ་བསྐུར་བའི་འཕྲིན་ཡིག
  author: ''
  volumes:
    b91538dd0d7b41e99afd494d332dcb03:
      image_group_id: I4CZ45280
      title: ''
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
